apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels: {{ - include "backend.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ - include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ - include "backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              value: {{ .Values.env.MLFLOW_S3_ENDPOINT_URL | quote }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.env.AWS_ACCESS_KEY_ID | quote }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.env.AWS_SECRET_ACCESS_KEY | quote }}
          resources: {{ - toYaml .Values.resources | nindent 12 }}
