provider:
  name: google
extraArgs:
  - --google-project=timebertt-dhbw
env:
- name: GOOGLE_APPLICATION_CREDENTIALS
  value: /etc/secrets/service-account/service-account.json
extraVolumeMounts:
- name: clouddns-credentials
  mountPath: /etc/secrets/service-account
  readOnly: true
extraVolumes:
- name: clouddns-credentials
  secret:
    secretName: google-clouddns
logLevel: info
policy: sync
interval: 5m
triggerLoopOnEvent: true
sources:
- ingress
- service

registry: txt
txtOwnerId: group-avgk # <cluster-name>, e.g., student-abcd